routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('dashboard/welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider')->where('provider','facebook|google|youtube');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback')->where('provider','facebook|google|youtube');

app/Playground.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Playground extends Model
{
    protected $table = 'playgrounds';
    protected $guarded = [];
    //Attribute -----------------------------------------
    /* To make any value in name column as UpperCase  */
    public function getNameAttribute ($value){
        return ucfirst($value);
    }//end of getAttribute

    //Relations -----------------------------------------
    public function users (){
        return $this->belongsToMany(User::class,'users_playground');
    }//end of floor

    //Scope ----------------------------------------------
    /* I use scope for i can call it easy from controller == so I can use it in controller as WhenSearch without scope */
    public function scopeWhenSearch($query , $search){
        return $query->when($search ,function ($q) use ($search){
            return $q->where('name','like',"%$search%");
        });

    }//end of scopeWhenSearch
}

app/Http/Controllers/Dashboard/AssignController.php
<?php

namespace App\Http\Controllers\Dashboard;
use App\Http\Controllers\Controller;

use App\Playground;
use App\User_Playground;
use Illuminate\Http\Request;

class AssignController extends Controller
{
    public function __construct()
    {
        //Parent Path
        $this->path = "dashboard.playgrounds.";
    }
    public function update  (Request $request, Playground $assign){

        foreach ($request->users as $user){
            User_Playground::create([
                'playground_id'=>$assign->id,
                'user_id'=>$user
            ]);
        }
        session()->flash('success',__('site.DataUpdatedSuccessfully'));
        return redirect()->route($this->path.'index');

    }//end of update
}

app/Http/Controllers/Dashboard/CategoryController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Category;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
     public function __construct()
         {
             //Parent Path
             $this->path = "dashboard.categories.";

         }

          public function index()
          {
              $categories = Category::WhenSearch(request()->search)->paginate(5);
              return view($this->path.'index',compact('categories'));
          }//end of index

          public function create()
          {
               return view($this->path.'create');
          }//end of create

          public function store(Request $request)
          {
              $request->validate([
                  'name' => 'required|unique:categories,name',
              ]);
              Category::create($request->all());
              session()->flash('success',__('site.DataAddSuccessfully'));
              return redirect()->route($this->path.'index');
          }//end of store

          public function show($id)
          {
              //
          }//end of show

          public function edit(Category $category)
          {
               return view($this->path.'create',compact('category'));
          }//end of edit

          public function update(Request $request, Category $category)
          {
              $request->validate([
                  'name' => 'required|unique:categories,name,'.$category->id,
              ]);
              $category->update($request->all());
              session()->flash('success',__('site.DataUpdatedSuccessfully'));
              return redirect()->route($this->path.'index');
          }//end of update

          public function destroy(Category $category)
          {
              $category->delete();
              session()->flash('success',__('site.DataDeletedSuccessfully'));
              return redirect()->route($this->path.'index');
          }//end of destroy
}

app/Http/Controllers/Dashboard/FloorController.php
<?php

namespace App\Http\Controllers\Dashboard;
use App\Floor;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;


class FloorController extends Controller
{
    public function __construct()
    {
        //Parent Path
        $this->path = "dashboard.floors.";

    }

    public function index()
    {
        $floors = Floor::WhenSearch(request()->search)->paginate(5);
        return view($this->path.'index',compact('floors'));
    }//end of index

    public function create()
    {
        return view($this->path.'create');
    }//end of create

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:floors,name',
            'level' => 'required',
            'numberOfRoom' => 'required|integer',
        ]);

        Floor::create($request->all());
        session()->flash('success',__('site.DataAddSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of store


    public function edit(Floor $floor)
    {
        return view($this->path.'create',compact('floor'));
    }//end of edit

    public function update(Request $request, Floor $floor)
    {
        $request->validate([
            'name' => 'required|unique:floors,name,'.$floor->id,
            'level' => 'required',
            'numberOfRoom' => 'required|integer',
        ]);
        $floor->update($request->all());
        session()->flash('success',__('site.DataUpdatedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of update

    public function destroy(Floor $floor)
    {
        $floor->delete();
        session()->flash('success',__('site.DataDeletedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of destroy
}

app/Http/Controllers/Dashboard/PlaygroundController.php
<?php

namespace App\Http\Controllers\Dashboard;
use App\Http\Controllers\Controller;
use App\Playground;
use App\User;
use App\User_Playground;
use Illuminate\Http\Request;

class PlaygroundController extends Controller
{
    public function __construct()
    {
        //Parent Path
        $this->path = "dashboard.playgrounds.";
    }

    public function index()
    {

        $playgrounds = Playground::WhenSearch(request()->search)
            ->withCount('users')
            ->paginate(5);
        return view($this->path.'index',compact('playgrounds'));
    }//end of index

    public function create()
    {
        $users = User::all();
        return view($this->path.'create',compact(['floors','users']));
    }//end of create

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:playgrounds,name',
        ]);

        Playground::create($request->all());
        session()->flash('success',__('site.DataAddSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of store

    public function show (Playground $playground){
        $show_playground = $playground;
        $users = User::all();
        return view($this->path.'create',compact(['show_playground','users']));


    }//end of show

    public function edit(Playground $playground)
    {
        $users = User::all();
        return view($this->path.'create',compact(['playground','users']));
    }//end of edit

    public function update(Request $request, Playground $playground )
    {
            $request->validate([
                'name' => 'required|unique:playgrounds,name,'.$playground->id,
            ]);
            $playground->update($request->all());


        session()->flash('success',__('site.DataUpdatedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of update

    public function destroy(Playground $playground)
    {
        $playground->delete();
        session()->flash('success',__('site.DataDeletedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of destroy
}

app/Http/Controllers/Dashboard/RoleController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{
    public function __construct()
    {
        // Parent Path
        $this->path = "dashboard.roles.";

        //Permissions
        $this->middleware('permission:read_roles')->only(['index']);
        $this->middleware('permission:create_roles')->only(['create','store']);
        $this->middleware('permission:update_roles')->only(['edit','update']);
        $this->middleware('permission:delete_roles')->only(['destroy']);
    }

    public function index()
    {
        $roles = Role::WhereRoleNot(['super_admin','admin'])
            ->WhenSearch(request()->search)
            ->with('permissions')
            ->withCount('users')
            ->paginate(5);
        return view($this->path.'index',compact('roles'));
    }//end of index

    public function create()
    {
        return view($this->path.'create');
    }//end of create

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|unique:roles,name',
            'permissions' => 'required|array|min:1',
        ]);
        $role = Role::create($request->all());
        $role->attachPermissions($request->permissions);

        session()->flash('success',__('site.DataAddSuccessfully'));
        return redirect()->route($this->path.'index');

    }//end of store

    public function edit(Role $role)
    {
        return view($this->path.'create',compact('role'));
    }//end of edit

    public function update(Request $request, Role $role)
    {
        $request->validate([
            'name' => 'required|unique:roles,name,'.$role->id,
            'permissions' => 'required|array|min:1',
        ]);
        $role->update($request->all());
        $role->syncPermissions($request->permissions);
        session()->flash('success',__('site.DataUpdatedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of update

    public function destroy(Role $role)
    {
        $role->delete();
        session()->flash('success',__('site.DataDeletedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of destroy
}

app/Http/Controllers/Dashboard/RoomController.php
<?php

namespace App\Http\Controllers\Dashboard;
use App\Floor;
use App\Http\Controllers\Controller;
use App\Room;
use App\User;
use Illuminate\Http\Request;

class RoomController extends Controller
{
    public function __construct()
    {
        //Parent Path
        $this->path = "dashboard.rooms.";
    }

    public function index()
    {
        $rooms = Room::WhenSearch(request()->search)
            ->with(['floor','user'])
            ->paginate(5);
        return view($this->path.'index',compact('rooms'));
    }//end of index

    public function create()
    {
        $floors = Floor::all();
        $users = User::all();
        return view($this->path.'create',compact(['floors','users']));
    }//end of create

    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|',
            'number' => 'required|',
            'user_id' => 'required|unique:rooms,user_id',
        ]);


        Room::create($request->all());
        session()->flash('success',__('site.DataAddSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of store


    public function edit(Room $room)
    {
        $floors = Floor::all();
        $users = User::all();
        return view($this->path.'create',compact(['room','floors','users']));
    }//end of edit

    public function update(Request $request, Room $room)
    {
        $request->validate([
            'name' => 'required|unique:rooms,name,'.$room->id,
            'number' => 'required|',
        ]);
        $room->update($request->all());
        session()->flash('success',__('site.DataUpdatedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of update

    public function destroy(Room $room)
    {
        $room->delete();
        session()->flash('success',__('site.DataDeletedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of destroy
}

app/Http/Controllers/Dashboard/UserController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Role;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    public function __construct()
    {
        //Parent Path
        $this->path = "dashboard.users.";
    }

    public function index()
    {
        $roles = Role::whereRoleNot(['super_admin'])->get();
        $users = User::WhereRoleNot(['super_admin'])
            ->WhenSearch(request()->search)
            ->whenRole(request()->role_id)
            ->with(['roles','room'])
            ->paginate(5);
        return view($this->path.'index',compact('roles','users'));
    }//end of index

    public function create()
    {
        $roles = Role::WhereRoleNot(['super_admin','admin'])->get();
        return view($this->path.'create',compact('roles'));
    }//end of create

    public function store(Request $request)
    {
//        dd($request->image->store('images','public'));
        $request->validate([
            'name' => 'required|min:2',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|confirmed|min:3',
            'image' => 'sometimes|nullable|image',
//            'role_id' => 'required|numeric',
        ]);

        $request->merge(['password'=>bcrypt($request->password)]);
        $data = $request->only(['name','email','password']);
        if ($request->hasFile('image')){
            $image = $request->image->store('images','public');
            $data['image'] = $image;
        }
//        dd($data);
        User::create($data);

        session()->flash('success',__('site.DataAddSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of store

    public function edit(User $user)
    {
        $roles = Role::WhereRoleNot(['super_admin','admin'])
//            ->with('roles')
            ->get();
        return view($this->path.'create',compact('user','roles'));
    }//end of edit

    public function update(Request $request, User $user)
    {

        $request->validate([
            'name' => 'required|min:2',
            'email' => 'required|email|unique:users,email,'.$user->id,
//            'password' => 'sometimes|nullable|confirmed',
            'image' => 'sometimes|nullable|image',
        ]);

        $data = $request->only(['name','email','password']);
        if ($request->hasFile('image')){
            $image = $request->image->store('images','public');
            Storage::disk('public')->delete($user->image);
            $data['image'] = $image;
        }
        $user->update($data);

        session()->flash('success',__('site.DataUpdatedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of update

    public function destroy(User $user)
    {
        $user->Delete();
        session()->flash('success',__('site.DataDeletedSuccessfully'));
        return redirect()->route($this->path.'index');
    }//end of destroy
}

app/Http/Controllers/Dashboard/welcomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class welcomeController extends Controller
{
    public function index (){
        return view('dashboard.welcome');
    }//end of function
}

resources/views/dashboard/playgrounds/create.blade.php
@extends('layouts.dashboard.app')

@section('content')
    <div class="app-title">
        <div>
            @if(isset($playground)  )
                <h1>
                    <i class="fa fa-edit">
                        {{ __('site.Update Playground')}}
                    </i>
                </h1>
            @elseif(isset($show_playground))
                <h1>
                    <i class="fa fa-edit">
                        {{ __('site.Assign players')}}
                    </i>
                </h1>
            @else
                <h1>
                    <i class="fa fa-plus">
                        {{__('site.Add Playground') }}
                    </i>
                </h1>
            @endif

        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-list"></i></li>
            {{--            <li class="breadcrumb-item"><a href="{{route('dashboard.welcome')}}">{{__('site.Dashboard')}}</a></li>--}}
            <li class="breadcrumb-item"><a href="{{route('dashboard.playgrounds.index')}}">{{__('site.Playground')}}</a></li>
            @if(isset($playground))
                <li class="breadcrumb-item"> {{ __('site.Update Playground')}}</li>
            @elseif(isset($show_playground))
                <li class="breadcrumb-item"> {{ __('site.Assign players')}}</li>
            @else
                <li class="breadcrumb-item"> {{__('site.Add Playground') }}</li>
            @endif
        </ul>
    </div>

    <div class="tile mb-4">
        <div class="row">
            <div class="col-md-12">
                <form action="{{ isset($playground)?route('dashboard.playgrounds.update',$playground->id) : isset($show_playground)?route('dashboard.assign.update',$show_playground->id): route('dashboard.playgrounds.store')  }}" method="post">
                    @csrf
                    @if(isset($playground))
                        @method('put')
                    @elseif(isset($show_playground))
                        @method('put')
                    @else
                        @method('post')
                    @endif

                    @include('dashboard.partials._errors')

                    <div class="form-group">
                        <label>{{__('site.name')}} :</label>
                        <input type="text" name="name" class="form-control" value="{{isset($playground)?$playground->name:"" || isset($show_playground)?$show_playground->name:"" }}">
                    </div>
                    @isset($show_playground)
                    <div class="form-group">
                        <label>{{__('site.users will play in')}} :</label>

                        <select name="users[]"  class="form-control select2" multiple>
                            @foreach( $users as $user )
                                @if( isset($show_playground) )
                                    <option
                                        value="{{$user->id}} "
                                        {{$show_playground->user?'selected':''}}
                                    >
                                        {{ $user->name}}
                                    </option>
                                @else
                                    <option value="{{$user->id}}">{{  $user->name}}</option>
                                @endif
                            @endforeach
                        </select>
                    </div>
                    @endisset


                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            @if( isset($playground) )
                                <i class="fa fa-edit"></i>
                                {{__('site.Update')}}
                            @elseif(isset($show_playground))
                                <i class="fa fa-plus"></i>
                                {{__('site.Add')}}
                            @else
                                <i class="fa fa-plus"></i>
                                {{__('site.Add')}}
                            @endif

                        </button>
                    </div>
                </form>

            </div>{{-- end-of-col-12 --}}
        </div>{{--end-of-row--}}


    </div>{{--end-of-tile mb-4--}}


@endsection

resources/views/dashboard/playgrounds/index.blade.php
@extends('layouts.dashboard.app')

@section('content')
    <div class="app-title">
        <div>
            <h1><i class="fa fa-list"></i> {{__('site.Playground')}}</h1>
        </div>
        <ul class="app-breadcrumb breadcrumb">
            <li class="breadcrumb-item"><i class="fa fa-home fa-lg"></i></li>
{{--            <li class="breadcrumb-item"><a href="{{route('dashboard.welcome')}}">{{__('site.Dashboard')}}</a></li>--}}
            <li class="breadcrumb-item">{{__('site.Playground')}}</li>
        </ul>
    </div>

    <div class="tile mb-4">
        <div class="row">
            <div class="col-md-12">
                {{-- this form for Search button                --}}
                <form action="" >
                    <div class="row">
                        <div class="col-md-4">
                            <div class="form-group">
                                <input type="text" name="search" autofocus class="form-control" placeholder="Search" value="{{request()->search}}">
                            </div>
                        </div>{{-- end-of-col-4 --}}


                        <div class="col-md-4">
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i>Search</button>
                                    <a href="{{route('dashboard.playgrounds.create')}}" class="btn btn-primary"><i class="fa fa-plus"></i> Add</a>
                            </div>
                        </div>{{-- end-of-col-4 --}}


                    </div>{{-- end-of-row --}}
                </form>{{-- end-of-form --}}

            </div>{{-- end-of-col-12 --}}
        </div>{{--end-of-row--}}

        <div class="row">
            <div class="col-md-12">
                <hr>
                @if($playgrounds->count() > 0 )
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>#</th>
                            <th>{{__('site.name')}} </th>
                            <th>{{__('site.users count')}} </th>
                            <th style="text-align: center">{{__('site.action')}}</th>
                        </tr>
                        </thead>
                        <tbody>
                        @isset($playgrounds)
                            @foreach($playgrounds as $index=>$playground)

                                <tr>
                                    <td>{{++$index}}</td>
                                    <td>{{$playground->name}}</td>
                                    <td>{{$playground->users_count}}
{{--                                        @foreach( $playground->users as $user )--}}
{{--                                            <span style="display: inline-block" class="badge badge-primary">{{$user->name}}</span>--}}
{{--                                        @endforeach--}}
                                    </td>
                                    <td style="text-align: center">
                                        {{--Edit buttom--}}
                                        <a href="{{route('dashboard.playgrounds.show', $playground->id)}}" class="btn btn-success btn-sm"><i class="fa fa-edit">Assign players</i></a>
                                        <a href="{{route('dashboard.playgrounds.edit', $playground->id)}}" class="btn btn-warning btn-sm"><i class="fa fa-edit">Edit</i></a>
                                        {{--Delete buttom--}}
                                        <form action="{{route('dashboard.playgrounds.destroy', $playground->id)}}" method="post" style="display: inline-block">
                                            @csrf
                                            @method('delete')
                                            <button type="submit" class="btn btn-danger btn-sm delete"><i class="fa fa-trash"></i>{{__('site.Delete')}}</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                        @endisset

                        </tbody>

                    </table>
                    {{$playgrounds->appends(request()->query())->links()}}
                @else
                    <h3 style="font-weight: 400; text-align: center"> No Record Found</h3>
                @endif
            </div>
        </div>

    </div>{{--end-of-tile mb-4--}}


@endsection